"""

author: whiteP

modified time: 2020/4/12 11:46

"""

# Generated by Selenium IDE
import json
import time
from typing import List, Dict

from selenium import webdriver
from selenium.webdriver.common.by import By


class Test123():
    def setup_method(self, method):
        chrome_opts = webdriver.ChromeOptions()
        chrome_opts.debugger_address = "127.0.0.1:9222"
        self.driver = webdriver.Chrome(options=chrome_opts)
        # self.driver = webdriver.Chrome()
        self.driver.get("https://work.weixin.qq.com/")
        self.driver.implicitly_wait(3)

    def teardown_method(self, method):
        self.driver.quit()

    def test_123(self):
        # self.driver.get("https://work.weixin.qq.com/")
        # self.driver.find_element(By.CSS_SELECTOR,
        #                          ".index_service_cnt_item_title").click()
        # time.sleep(15)
        cookies = self.driver.get_cookies()
        with open("cookies.txt", "w") as f:
            json.dump(cookies, f)
        with open("cookies.txt", "r") as f:
            cookies: List[Dict] = json.load(f)
        for cookie in cookies:
            if "expiry" in cookie.keys():
                cookie.pop("expiry")
            self.driver.add_cookie(cookie)
        self.driver.get("https://work.weixin.qq.com/wework_admin/frame#index")
        self.driver.find_element(By.CSS_SELECTOR,
                                 '.index_service_cnt_itemWrap').click()
        # self.driver.find_element(By.CSS_SELECTOR, "#username").\
        #     send_keys("hello")
        # self.driver.find_element(By.XPATH, '//*[@id="memberAdd_acctid"]').\
        #     send_keys("hello2")
